name: Java CI/CD with Gradle and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Echo Message
        run: echo "Hi, I am from COSC 1209 class"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Grant execute permission to Gradle wrapper (Linux/macOS only)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Setup Java
        uses: acti
